// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geabskxjfkmqcgrqhfra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlYWJza3hqZmttcWNncnFoZnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTIxMzgsImV4cCI6MjA2MDQ4ODEzOH0.luIxzeeSfPs42MSDNX-KVgbQNfFEKJY7TPvXGSXjDtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);